#!/usr/bin/env bash
# scrip to install nginx on a server
apt-get update -y
apt-get install -y nginx

echo 'Hello World!' > /var/www/html/index.nginx-debian.html

printf %s "server {
  listen 80;
  listen [::]:80 default_server;

  root   /etc/nginx/html;
  index  index.html index.htm;

  location /redirect_me {
    return 301 https://github.com/Mcrymbo/;
  }" > /etc/nginx/sites-available/default

service nginx start
