#!/usr/bin/env bash
# scrip to install nginx on a server
apt-get update -y
apt-get install -y nginx

echo 'Hello World!' > /var/www/html/index.nginx-debian.html

sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Mcrymbo permanent;/" /etc/nginx/sites-available/default

service nginx start
