#!/usr/bin/env bash
# install and configure HAproxy on lb-01
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*

echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 325266-web-01 100.26.121.3:80 check\n\tserver 325266-web-02 100.26.159.29:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart
