#!/usr/bin/env bash
#Telling a story of passwd

while IFS= read -r line; do
	username=$(echo "$line" | cut -f 1 -d ':')
	password=$(echo "$line" | cut -f 2 -d ':')
	userID=$(echo "$line" | cut -f 3 -d ':')
	grpid=$(echo "$line" | cut -f 4 -d ':')
	userINFO=$(echo "$line" | cut -f 5 -d ':')
	home=$(echo "$line" | cut -f 6 -d ':')
	cmd=$(echo "$line" | cut -f 7 -d ':')

	echo -n "The user $username is part of the $grpid gang, "
	echo -n "lives in $home and rides $cmd. "
	echo -n "$userID place is protected by the passcode $password, "
	echo "more info about the user here: $userINFO"

done < /etc/passwd
