#!/usr/bin/env bash
# Using if cndition on the 9th iteration

count=0
while [ $count -lt 10 ]; do
	if [ $count -eq 8 ]; then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	count=$((count + 1))
done
