#!/usr/bin/env bash
# prints "bad luck" for 4th count and "good luck" for 8th count

count=1
while [ $count -le 10 ]; do
	if [ $count -eq 4 ]; then
		echo "bad luck"
	elif [ $count -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi

	count=$((count + 1))
done
