#!/usr/bin/env bash
# script that provides information about school file

file="school"
if [ -e "$file" ]; then
	echo "school file exists"
	
	if [ -s "$file" ]; then
		echo "school file is not empty"
	else
		echo "school is not empty"
	fi

	if [ -f "$file" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
