#!/usr/bin/env bash
# adds new ip addreses to the system

cp /etc/hosts ~/hosts.copy
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.copy
sed -i '2i8.8.8.8 facebook.com' ~/hosts.copy
cp -f ~/hosts.copy /etc/hosts
